### ISSUE TITLE
Create chat server backend: checklist

### ISSUE THREAD

**Issue by omdxp** [Younext19/Chatty#1]
- [ ] init gomodule for backend
- [ ] create websocket endpoint
- [ ] chatroom up to specific amount of users
